API_KEY = ''
API_SECRET = ''

# OPTIONAL **************************
IS_MFA_ENABLED = False

PHONE_NUM = '12016768877'
SECURITY_QUESTION_ID = ''
CUSTOM_OBJECT_NAME = ''

CANDIDATE_TOKEN = ''
FACEBOOK_TOKEN = ''
TWITTER_TOKEN = ''
TWITTER_SECRET = ''
VKONTAKTE_TOKEN = ''
GOOGLE_TOKEN = ''

REGISTRATIONDATA_TYPE = ''
REGISTRATIONDATA_RECORDID = ''
# ***********************************